### ISSUE TITLE
Học hỏi kinh nghiệm

### ISSUE THREAD

**Issue by ngoctuannguyen** [tien02/ensemble_phobert_fasttext_vietnamese_SentAnalysis#2]
Em chào anh ạ,
Em hiện đang là sinh viên năm 2 và cũng có định hướng chuyên sâu về mảng NLP. Trong lúc tìm kiếm các project để tham khảo, học hỏi thêm kinh nghiệm để chuẩn bị hành trang tốt nhất cho tương lai, em thấy có hứng thú đối với project này của anh và có mong muốn được hiểu cách tiếp cận về thiết kế một project. Không biết là anh có thể chia sẻ về quy trình, các bước khi anh bắt tay vào làm project này có được không ạ ?
Em cảm ơn anh ạ.

**Comment by tien02** [comment]
Hello @ngoctuannguyen, cảm ơn em đã quan tâm tới project của anh. Đây là một chút chia sẻ của anh khi tiếp cận bài toán về AI.

Trước tiên, để tránh việc "phát minh lại bánh xe", anh sẽ tham khảo các dự án tương tự trước khi đưa ra các quyết định thiết kế cụ thể. Đôi khi chỉ cần chỉnh sửa vài thành phần là đủ. Khi phải implement from scratch, cần xác định các thành phần chính, module hóa chúng để dễ bảo trì và biết tận dụng các framework có sẵn.

Nhìn chung gồm có:
1. Xử lý dữ liệu: Từ raw data (folder ảnh, file .csv,...) -> batch of tensor. Cần phân tích, quan sát dữ liệu kĩ càng để có giải pháp triển khai phù hợp.
2. Thiết kế mô hình: Tự triển khai, hoặc tận dụng pretrain model, chỉnh sửa một số thành phần nếu cần thiết (head layer cho số lượng label trong bài toán classification chẳng hạn).
3. Training-Testing-Logging: Các framework lớn thường hỗ trợ xử lý quá trình Train-Test rất tốt và cả Logging để theo dõi quá trình huấn luyện.

Cần research, tham khảo document để hiểu rõ mô hình, objective function, cách các component hoạt động, sau đó triển khai và thực nghiệm. Ngoài ra cần kiến thức về Linear Algebra để giải quyết các vấn đề về dimension của tensor.

Hi vọng em sẽ thấy hữu ích.

**Comment by ngoctuannguyen** [comment]
Dạ vâng anh ạ, em đã hiểu và cảm ơn anh rất nhiều ạ.
